CREATE TABLE ADDRESS (
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 STREET VARCHAR(100),
 NUMBER INT NOT NULL,
 DISTRICT VARCHAR(50),
 CITY VARCHAR(50),
 STATE VARCHAR(2),
 ZIPCODE VARCHAR(9) NOT NULL
)engine=InnoDB;