CREATE TABLE ADDRESS (
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 STREET VARCHAR(50),
 NUMBER INT NOT NULL,
 DISTRICT VARCHAR(50),
 CITY VARCHAR(50),
 STATE VARCHAR(50),
 ZIPCODE INT(8) NOT NULL
)engine=InnoDB;