CREATE TABLE ITEM (
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(100) NOT NULL,
 CREATION_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 EXPIRATION_DATE TIMESTAMP,
 PRICE DECIMAL(10,2) NOT NULL,
 DESCRIPTION VARCHAR (200)
)engine=InnoDB;