CREATE TABLE ORDERS (
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 CPF VARCHAR(11) NOT NULL,
 TOTAL DECIMAL(10,2),
 ITEM_ID BIGINT,
 ADDRESS_ID BIGINT
)engine=InnoDB;

ALTER TABLE ORDERS ADD CONSTRAINT FK_ITEM_ORDERS FOREIGN KEY(ITEM_ID) REFERENCES ITEM (ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ADDRESS_ORDERS FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS (ID);