CREATE TABLE ITEM (
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(100) NOT NULL,
 CREATION_DATE DATE,
 EXPIRATION_DATE DATE NOT NULL,
 PRICE DECIMAL(10,2) NOT NULL,
 DESCRIPTION VARCHAR (200),
 ORDERS_ID BIGINT
)engine=InnoDB;

ALTER TABLE ITEM ADD CONSTRAINT FK_ORDERS_ITEM FOREIGN KEY(ORDERS_ID) REFERENCES ORDERS (ID);